### ISSUE TITLE
URL validation

### ISSUE THREAD

**Issue by sepandhaghighi** [openscilab/mybutton#12]
Currently, our website only supports the `http(s)` protocol. However, in some scenarios, users need to share other protocols/schemes such as `tg://`, `viber://` and ... .
To accommodate this, we should allow users to share any protocol/scheme link they want.

Example:

`<a href="mailto:?subject=&body=tg://msg?text = www.example.com?t=12" target="_blank"><img src="https://github.com/openscilab/mybutton/raw/main/src/Assets/icons/services/email.svg" width="32" height="32" style="background-color:#888990; border-radius:4px"/></a>`

**My suggestions:**

1. Remove validation on `URL` and also we can rename it to something like `Body`!

2. Create validation rules that can accommodate various protocols/schemes

**Comment by AHReccese** [comment]
update `URL` and `Page URL` to `link`
@F-Shahali
