### ISSUE TITLE
[Bug]: indirect mode doesn't work according to the way of parsing URL in the gh-pages gateway.

### ISSUE THREAD

**Issue by AHReccese** [openscilab/mybutton#26]
### Contact details

Telegram + Email

### What happened?

When using the indirect mode in production, the redirected URL doesn't work according to a `file not found` error.

Tip to resolve: 

- Add a query param instead of handling with "/", like `?share=indirect` instead of `/share` [recommended] 
- Add associated codes for the indirect mode in an `index.html` inside a folder named `share` in the root directory [not recommended]
- using Hashtag

### Steps to reproduce

try clicking on this: `https://mybutton.click/share/?service=gmail&subject=Hi!&link=http://openscilab.com`

### Expected behavior

Same behavior as the direct mode after getting redirected. 

### Actual behavior

`gh-pages` took `?service=gmail&subject=Hi!&link=http://openscilab.com` as a static file in the `share` folder of the root. Obviously there isn't such a file and a not found error pops out.

### Device type

Desktop

### Browser

Chrome

### MyButton version

MyButton 0.1

**Comment by AHReccese** [comment]
@F-Shahali Hi, Can you handle this issue this week?

**Comment by F-Shahali** [comment]
> @F-Shahali Hi, Can you handle this issue this week?

Yes, I'm working on this and it's almost done.
