### ISSUE TITLE
[Feature]: add Logo

### ISSUE THREAD

**Issue by AHReccese** [openscilab/mybutton#27]
### Describe the feature you want to add

add MyButton Logo to the project

- OpenGraph Tags
- README
- anywhere suitable

**Comment by AHReccese** [comment]
Hi dear Shahali, I think I've sent you the logo materials right? If I didn't, please let me know and If I did, let's go.

**Comment by F-Shahali** [comment]
> @F-Shahali Hi dear Shahali, I think I've sent you the logo materials right? If I didn't, please let me know and If I did, let's go.

Hi Mr. Rostami, yeah you're right. But this issue has been addressed and the related PR has been merged. Do I need to do anything else?

**Comment by AHReccese** [comment]
> > @F-Shahali Hi dear Shahali, I think I've sent you the logo materials right? If I didn't, please let me know and If I did, let's go.
> 
> Hi Mr. Rostami, yeah you're right. But this issue has been addressed and the related PR has been merged. Do I need to do anything else?

OK, great. So far so good.
Thanks for your prompt answer.

**Comment by AHReccese** [comment]
<img width="249" alt="image" src="https://github.com/user-attachments/assets/d2441bbc-88f0-4b90-bdc2-a9ef6122bbbf">

I linked this issue to the associated PR.
sometimes an issue is getting handled through more than one pull request, and it is better to mention each portion of enhancement in each PR's description (plus tagging the issue like `#23`), and finally in the last PR, it is better to add the associated issue in the `development` option of the last PR.

**Comment by F-Shahali** [comment]
> <img alt="image" width="249" src="https://private-user-images.githubusercontent.com/32750909/366980375-d2441bbc-88f0-4b90-bdc2-a9ef6122bbbf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxNjA3NjQsIm5iZiI6MTcyNjE2MDQ2NCwicGF0aCI6Ii8zMjc1MDkwOS8zNjY5ODAzNzUtZDI0NDFiYmMtODhmMC00YjkwLWJkYzItYTllZjYxMjJiYmJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEyVDE3MDEwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA5OWIzNWQ4NGFlNmM1OTU1NGU4NjA3MDU3M2U1OTBlYzZjYzQ0ODAzMWQ2ZmJlZjkyZmNiMzE0MjlmNDM0MDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._acge71Idh5vcB9H4pIHJ869-mFR52avt8DoQ4th5ZI">
> I linked this issue to the associated PR. sometimes an issue is getting handled through more than one pull request, and it is better to mention each portion of enhancement in each PR's description (plus tagging the issue like `#23`), and finally in the last PR, it is better to add the associated issue in the `development` option of the last PR.

OK, thanks for mentioning this point.
